# Generated by Django 3.0.7 on 2020-08-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
